version: "3.9"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: the-ethereum-fetcher
      POSTGRES_PASSWORD: Zgahbwm+qp3GNG4R
      POSTGRES_DB: main
    ports:
      - "5432:5432"
